services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEBHOOK_URL
        value: https://twist-snack-bot-1-0-1.onrender.com